version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: kitra_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kitra_root_password
      MYSQL_DATABASE: kitra_db
      MYSQL_USER: kitra_user
      MYSQL_PASSWORD: kitra_password
    ports:
      - "3306:3306"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql